# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed

title: CI/CS Workshop
tagline: The Community Together

description: >-
  The 2020 Cyberinfrastructure/Cybersecurity Workshop: A virtual
  training event for cybersecurity and cyberinfrastructure
  professionals

url: 'https://cics-workshop.org'

author: CI/CS Workshop

avatar: /assets/img/logo.jpg

github:
  username: github_username             # change to your github username

twitter:
  username: twitter_username            # change to your twitter username

social:
  name: your_full_name                  # it will shows as the copyright owner in Footer
  email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/username       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: UA-18066333-15

#--------------------------

baseurl: ''
timezone: America/Los_Angeles

google_analytics:
  id: 'UA-18066333-15'
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

disqus:
  comments: false
  shortname: ''


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dark

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp,
            optgroup, option, colgroup, caption,
            thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE
  - .idea

sitemap_exclude:
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
